services:
  postgresql:
    image: postgis/postgis:16-master
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: room-rent
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data: