services:
  postgresql:
    image: postgis/postgis:16-master
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: room-rent
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - postgresql_bd_net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-password}
    ports:
      - "5555:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - postgresql_bd_net
    depends_on:
      - postgresql

volumes:
  postgresql-data:
  pgadmin-data:

networks:
    postgresql_bd_net:
